### ISSUE TITLE
all exported (public) struct members should have a verbose variable name

### ISSUE THREAD

**Issue by oryband** [gima/jsonv#8]
e.g. https://github.com/gima/jsonv/blob/master/src/optional.go#L13
I've noticed that if for example I have a schema with the following field validation:
```go
// ...
{"number_field", &j.Optional{&j.Number{Min: 1}}},
// ...
```
The executing `go vet` returns:
```sh
config.go:115: github.com/gima/jsonv/src.Optional composite literal uses unkeyed fields
exit status 1
```
Which practically forces me to add `Optional.V` in the line:
```go
{"number_field", &j.Optional{V: &j.Number{Min: 1}}},
```
But having that big `V` is quite unclear and non-verbose.

**Comment by gima** [comment]
Closed as a result of discussion in issue #3.
